# Generated by Django 5.0.2 on 2024-02-27 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bx_id', models.IntegerField()),
                ('planup_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Оформлено'), (2, 'В процессе'), (3, 'Выполнено')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cheklist.applications')),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheklist.status'),
        ),
    ]
