# Generated by Django 5.0.2 on 2024-02-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='URL'),
        ),
    ]
