# Generated by Django 5.0.2 on 2024-02-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheklist', '0002_alter_applications_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrating',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
