# Generated by Django 5.0.2 on 2024-02-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheklist', '0003_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Оформлено', 'Оформлено'), ('В процессе', 'В процессе'), ('Выполнено', 'Выполнено')], max_length=15),
        ),
    ]
