# Generated by Django 5.0.2 on 2024-02-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheklist', '0003_applicationrating_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrating',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cheklist.applications'),
        ),
    ]
