# Generated by Django 5.0.2 on 2024-02-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheklist', '0004_alter_applicationrating_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[(0, 'Оформлено'), (1, 'В процессе'), (2, 'Выполнено')], max_length=15),
        ),
    ]
