# Generated by Django 5.0.2 on 2024-02-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheklist', '0004_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
