# Generated by Django 5.0.2 on 2024-02-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheklist', '0005_alter_applications_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='user_id',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
