# Generated by Django 5.0.2 on 2024-02-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheklist', '0005_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Оформлено', 1), ('В процессе', 2), ('Выполнено', 3)], max_length=15),
        ),
    ]
